name: CI

on:
  pull_request:
    branches: 
      -main

jobs:
  ci:
    runs-on: unbuntu-latest
    name: Lint and test

    steps:
          - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Test
        run: npm test
